
version: '3.9'

services:
  web:
    build: .
    container_name: gincana_web
    command: gunicorn gincana.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8787:8000"

  nginx:
    image: nginx:alpine
    container_name: gincana_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/staticfiles
    depends_on:
      - web

volumes:
  static_volume:
