# Generated by Django 5.2 on 2025-10-23 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crianca',
            name='idade',
            field=models.PositiveSmallIntegerField(default=0, help_text='Idade da criança em anos (0–12).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)]),
            preserve_default=False,
        ),
    ]
